package view;


import dao.ServicoDao;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sepultura;
import model.Servico;
import model.Usuario;
import view.Menu;

public class TelaAvisos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAvisos.class.getName());
    
    private Usuario usuarioAutenticado;
    
     //construtor que está recebendo o usuario que foi autenticado na tela de login
    public TelaAvisos(Usuario usuario){
        initComponents();
        this.usuarioAutenticado = usuario;
        preencherTabelaAvisos();
        } 
    
    private void preencherTabelaAvisos() {
    DefaultTableModel modeloPendentes = (DefaultTableModel) tblServicosPendentes.getModel();
    DefaultTableModel modeloGeral = (DefaultTableModel) tblAvisosGerais.getModel();
    modeloPendentes.setRowCount(0);
    modeloGeral.setRowCount(0);
    
    ServicoDao sDao = new ServicoDao();

    
    for (Servico s : sDao.listarTodos()) {
        if(s.getStatusServico().equalsIgnoreCase("Pendente")){
            modeloPendentes.addRow(new Object[]{ 
                s.getIdServico(),
                s.getTipoServico(),
                s.getNotificacaoServico()
            });
        }
        if(s.getNotificacaoServico() != null && !s.getNotificacaoServico().isBlank() ){
            modeloGeral.addRow(new Object[]{ 
                s.getIdServico(),
                s.getTipoServico(),
                s.getStatusServico(),
                s.getNotificacaoServico()
            });

        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicosPendentes = new javax.swing.JTable();
        lblAvisosGerais = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvisosGerais = new javax.swing.JTable();
        lblServicosPendentes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloServicos = new javax.swing.JLabel();
        btnVoltarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        tblServicosPendentes.setBackground(new java.awt.Color(0, 102, 102));
        tblServicosPendentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        tblServicosPendentes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblServicosPendentes.setForeground(new java.awt.Color(255, 255, 255));
        tblServicosPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo de Serviço", "Notificação interna"
            }
        ));
        jScrollPane1.setViewportView(tblServicosPendentes);

        lblAvisosGerais.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAvisosGerais.setForeground(new java.awt.Color(255, 255, 255));
        lblAvisosGerais.setText("Notificações gerais");

        tblAvisosGerais.setBackground(new java.awt.Color(0, 102, 102));
        tblAvisosGerais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        tblAvisosGerais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblAvisosGerais.setForeground(new java.awt.Color(255, 255, 255));
        tblAvisosGerais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo de Serviço", "Status", "Notificação interna"
            }
        ));
        jScrollPane2.setViewportView(tblAvisosGerais);

        lblServicosPendentes.setBackground(new java.awt.Color(255, 255, 255));
        lblServicosPendentes.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblServicosPendentes.setForeground(new java.awt.Color(255, 255, 255));
        lblServicosPendentes.setText("URGENTE: Serviços pendentes");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloServicos.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        lblTituloServicos.setForeground(new java.awt.Color(0, 102, 102));
        lblTituloServicos.setText("Notificações internas");

        btnVoltarMenu.setForeground(new java.awt.Color(0, 102, 102));
        btnVoltarMenu.setText("Voltar ao Menu");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logoretangular.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnVoltarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloServicos)
                .addGap(296, 296, 296)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloServicos)
                    .addComponent(btnVoltarMenu))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServicosPendentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvisosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 34, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblAvisosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServicosPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(usuarioAutenticado);  
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvisosGerais;
    private javax.swing.JLabel lblServicosPendentes;
    private javax.swing.JLabel lblTituloServicos;
    private javax.swing.JTable tblAvisosGerais;
    private javax.swing.JTable tblServicosPendentes;
    // End of variables declaration//GEN-END:variables
}
